trigger:
- release*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- script: |
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    echo Unified Agent downloaded successfully
    java -jar wss-unified-agent.jar -d "./dotnetcore-sample"
  env:
    WS_APIKEY: $(APIKEY)
    WS_USERKEY: $(USERKEY)
    WS_PRODUCTNAME: $(System.TeamProject)
    WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
    WS_FILESYSTEMSCAN: false
    WS_CHECKPOLICIES: true
    WS_FORCECHECKALLDEPENDENCIES: true
    WS_FORCEUPDATE: true
    WS_FORCEUPDATE_FAILBUILDONPOLICYVIOLATION: true
    WS_GENERATEPROJECTDETAILSJSON: true
    WS_EXCLUDES: '**/build/** **/tests/**'
  displayName: 'Unified Agent Scan'

- pwsh: |
    $apiURL = 'https://saas.whitesourcesoftware.com/api/v1.3'
    $ProjDetailsObj = Get-Content $(Build.SourcesDirectory)/whitesource/scanProjectDetails.json | ConvertFrom-Json
    echo projectToken = $ProjDetailsObj.projects.projectToken
    echo userKey = $(USERKEY)
    Invoke-WebRequest -OutFile "./whitesource/VulnerabilityReport.xlsx" -UseBasicParsing "https://saas.whitesourcesoftware.com/api/v1.3" -ContentType "application/json" -Method POST -Body "{ 'requestType':'getProjectVulnerabilityReport', 'userKey':$(USERKEY), 'projectToken':$ProjDetailsObj.projects.projectToken}"
    Invoke-WebRequest -OutFile "./whitesource/RiskReport.pdf" -UseBasicParsing "https://saas.whitesourcesoftware.com/api/v1.3" -ContentType "application/json" -Method POST -Body "{ 'requestType':'getProjectRiskReport', 'userKey':$(USERKEY), 'projectToken':$ProjDetailsObj.projects.projectToken}"
    Invoke-WebRequest -OutFile "./whitesource/DueDiligenceReport.xlsx" -UseBasicParsing "https://saas.whitesourcesoftware.com/api/v1.3" -ContentType "application/json" -Method POST -Body "{ 'requestType':'getProjectDueDiligenceReport', 'userKey':$(USERKEY), 'projectToken':$ProjDetailsObj.projects.projectToken}"
  displayName: 'Pipeline Reports'
  condition: succeededOrFailed()
  
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/whitesource'
    contents: |
      index.html
      checkPolicies-json.txt
      policyRejectionSummary.json
      VulnerabilityReport.xlsx
      RiskReport.pdf
      DueDiligenceReport.xlsx
    targetFolder: '$(Build.ArtifactStagingDirectory)/whitesource'
  condition: succeededOrFailed()

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/whitesource'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/whitesource.zip'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/whitesource.zip'
    artifact: 'WitheSource'
  condition: succeededOrFailed()
