trigger:
- release*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- script: |
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    echo Unified Agent downloaded successfully
    java -jar wss-unified-agent.jar -d "./dotnetcore-sample"
  env:
    WS_APIKEY: $(APIKEY)
    WS_USERKEY: $(USERKEY)
    WS_PRODUCTNAME: $(System.TeamProject)
    WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
    WS_FILESYSTEMSCAN: false
    WS_CHECKPOLICIES: true
    WS_FORCECHECKALLDEPENDENCIES: true
    WS_FORCEUPDATE: true
    WS_FORCEUPDATE_FAILBUILDONPOLICYVIOLATION: true
    WS_GENERATEPROJECTDETAILSJSON: true
    WS_EXCLUDES: '**/build/** **/tests/**'
  displayName: 'Unified Agent Scan'

- pwsh: |
    $outputsObject = Get-Content $(Build.SourcesDirectory)/whitesource/scanProjectDetails.json | ConvertFrom-Json
    echo outputsObject = $outputsObject
    echo outputsObject.projectToken = $outputsObject.projects.projectToken
  displayName: 'Parse ARM deploymentOutputs | pwsh'
  condition: succeededOrFailed()
  env:
    ARM_OUTPUTS: $(armOutputs)
- script: echo someResourceUriPwsh=$(someResourceUriPwsh)
  displayName: 'Log someResourceUriPwsh'
  condition: succeededOrFailed()

- script: |
    set WS_PROJECTTOKEN=$(jq -r '.projects | .[] | .projectToken' ./whitesource/scanProjectDetails.json)
    echo Unified $WS_PROJECTTOKEN
  displayName: 'Project token' 
  condition: succeededOrFailed()

- script: |
    set API_URL='https://saas.whitesourcesoftware.com/api/v1.3'
    echo API_URL=$API_URL
    curl --output ./whitesource/VulnerabilityReport.xlsx --request POST $API_URL --header "Content-Type: application/json" -d "{"requestType":"getProjectVulnerabilityReport", "userKey":$(USERKEY), "projectToken":"1ba878c5e5744f5381bdbcff5423e4a90ca1f2a22d82442fa39569e4489dc661"}"
    curl --output ./whitesource/RiskReport.pdf --request POST $API_URL --header "Content-Type: application/json" -d "{"requestType":"getProjectRiskReport", "userKey":$(USERKEY), "projectToken":"1ba878c5e5744f5381bdbcff5423e4a90ca1f2a22d82442fa39569e4489dc661"}"
    curl --output ./whitesource/DueDiligenceReport.xlsx --request POST $API_URL --header "Content-Type: application/json" -d "{"requestType":"getProjectDueDiligenceReport", "userKey":$(USERKEY), "projectToken":"1ba878c5e5744f5381bdbcff5423e4a90ca1f2a22d82442fa39569e4489dc661"}"
  displayName: 'Pipeline Reports' 
  condition: succeededOrFailed()
  
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/whitesource'
    contents: |
      index.html
      checkPolicies-json.txt
      policyRejectionSummary.json
      VulnerabilityReport.xlsx
      RiskReport.pdf
      DueDiligenceReport.xlsx
      scanProjectDetails.json
    targetFolder: '$(Build.ArtifactStagingDirectory)/whitesource'
  condition: succeededOrFailed()

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/whitesource'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/whitesource.zip'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/whitesource.zip'
    artifact: 'WitheSource'
  condition: succeededOrFailed()
